# Generated by Django 3.2.9 on 2022-02-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype'),
        ),
    ]
