# Generated by Django 3.2.9 on 2022-02-23 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_jobtype_job_job_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('updated_at', 'created_at')},
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
