# Generated by Django 3.2.9 on 2022-02-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['id']},
        ),
    ]
